### ISSUE TITLE
NvPipe_DecodeTexture hangs if NvPipe_EncodeTexture is not used first

### ISSUE THREAD

**Issue by omaralvarez** [NVIDIA/NvPipe#16]
When separating example code in two independent processes ```NvPipe_DecodeTexture``` hangs indefinitely. This can be reproduced in the EGL example commenting the encoder lines and using a 0 initialized vector in the decoder.

```cpp
uint64_t r = NvPipe_DecodeTexture(decoder, compressed.data(), size, clientColorTex, GL_TEXTURE_2D, width, height);
```

**Comment by tbiedert** [comment]
Hi Omar,

thanks for your feedback!

The decode function expects the bitstream of a complete frame. If you only feed in a partial packet or a dummy vector, the decode call will never return.  (Side note: But I agree that behavior could be improved, i.e., an error message should be printed. I will look into it.)

In your separated processes, can you please verify that you send/forward the complete encoded output of a single frame from the encode-process to the decode-process?

**Comment by omaralvarez** [comment]
I already tested that using ```NvPipe_Decode``` everything works fine. There is some corruption on the decoded frame, but it may be due to my network code, which was really really shady. The code is not yet available, because to be honest is not very robust. I want to use ZeroMQ for comms, because it will be less prone to mistakes. 

The GL client code was also really crappy, but did render in real time and sent a signal to the server so that the triangle changes size, that is how I found out captureFramebufferPPM needed to be called every frame.

**Comment by tbiedert** [comment]
A while ago I did a [comprehensive case study](http://biedert.de/publications/Streaming-EGPGV2018.pdf) about hardware-accelerated multi-tile streaming for remote sci vis applications, in which I used a prototype of NvPipe.

I realized that a standard TCP connection provided good results; I was even using the blocking write/read calls of Boost.Asio. However, as outlined in the paper, rendering/frame grab, encoding and sending was decoupled using multiple threads connected through queues (similar on decode-side). In this case, you can not use the convenience OpenGL-API of NvPipe, but need to perform manual frame grab through CUDA/GL interop in the rendering thread, push the raw image data on to a buffer/queue in device memory, and use the standard CUDA-based encode call in a different thread. You could even push it directly on to the network socket afterwards, without an additional networking thread, which probably has negligible performance impact. Overlapping rendering and encoding is worthwhile, though.  

I will close this issue for now. If you determine that your networking is solid (maybe do a quick checksum?), but still get issues with NvPipe, please feel free to reopen!

**Comment by omaralvarez** [comment]
My network code is not the best, but I still think ```NvPipe_DecodeTexture``` should be fixed so it does not block. You can reproduce it using that function in the file example without the encoder. What I mean is that my network code has nothing to do with ```NvPipe_DecodeTexture``` hanging.

**Comment by tbiedert** [comment]
Thanks for the clarification!

Can you please post some info on your setup (GPU, driver, OS etc)?

Also, please share a minimal code example that I can run to reproduce the error you’re seeing.

Note that I have pushed a small update to NvPipe in the meantime which now produces an error if a frame can not be decoded instead of looping. However, this obviously does not help if the input is not valid.

Thanks!
