### ISSUE TITLE
captureFramebufferPPM needs to be called in order to render frame in EGL example

### ISSUE THREAD

**Issue by omaralvarez** [NVIDIA/NvPipe#17]
If ```captureFramebufferPPM``` is not called, texture will not be updated. As is now, it only will encode first frame over and over again, since texture is only updated once.

```cpp
if (i == 0)
            captureFramebufferPPM(serverFBO, width, height, "egl-input.ppm");
```

**Comment by tbiedert** [comment]
Hi Omar, thanks for this valuable feedback!

The things you mentioned are in fact two different aspects:
- The EGL example currently renders the same scene over and over again, so subsequent frames do not differ. I will add a small rotation :-)

- You discovered an important issue:  Before grabbing the frame for encode (which internally uses CUDA/GL interop), OpenGL rendering needs to be finished. The `glReadPixels` in `captureFramebufferPPM` implicitly provided a barrier. For this simple example I will add a `glFinish` to make this clear. Thanks!
