### ISSUE TITLE
support d3d texture ?

### ISSUE THREAD

**Issue by zhaokaixs** [NVIDIA/NvPipe#18]
:)

**Comment by tbiedert** [comment]
Hi, thanks for this proposal! 

A Direct3D convenience API is currently not planned for NvPipe. 

I suggest using CUDA's Direct3D interop API to map textures into device memory and use `NvPipe_Encode`/`NvPipe_Decode`. 

Feel free to check out the OpenGL path in NvPipe for some inspiration.

Best,
Tim
