### ISSUE TITLE
How to control the quality and inter-frame structure?

### ISSUE THREAD

**Issue by Luyang1125** [NVIDIA/NvPipe#2]
Hi,

I want to know how can I control the encoding quality using this library, and how can I encode frame as P or B frames? Thanks!

**Comment by tfogal** [comment]
NVPipe explicitly is against letting you control this from the API: it's meant to be simple.

That said, if you want to hack the source then this is mostly in `nvp_config` from `encode.c`.  You'll need to grok [the video codec SDK (https://developer.nvidia.com/nvidia-video-codec-sdk) documentation as well.
