### ISSUE TITLE
NvPipe_Destroy(decoder); is missing in

### ISSUE THREAD

**Issue by hoene** [NVIDIA/NvPipe#22]
https://github.com/NVIDIA/NvPipe/blob/fe7268f407aa31889e651c4d6715b9d027679e77/examples/file.cpp#L137

**Comment by tbiedert** [comment]
Thanks! Fixed in https://github.com/NVIDIA/NvPipe/commit/4c5b20c063c822d0891471150fafb7839d43c74d
