### ISSUE TITLE
An C interface to Reconfigure()

### ISSUE THREAD

**Issue by hoene** [NVIDIA/NvPipe#24]
is missing.

Shall I write it?

**Comment by tbiedert** [comment]
Thanks for reaching out! So which Reconfigure() call do you mean exactly?

Resizing for instance happens automatically whenever the resolution parameters change.

Do you want to change the bitrate on the fly?  Would simply destroying and recreating a new encoder instance be a solution in your case?

**Comment by hoene** [comment]
Destroying and recreating take too much time...

Thus, I started to write something like this:
https://github.com/hoene/NvPipe/commit/d4b3970c45d5e8cbbba7027718932c384420c143

Is this the right way?

**Comment by tbiedert** [comment]
Thanks, this looks like a good start!

Two things that I noticed:

1) `memset(&reconfigureParams,0,sizeof(config));`  should be `memset(&reconfigureParams,0,sizeof(reconfigureParams));`

2) 
 ```
reconfigureParams.reInitEncodeParams.frameRateNum = targetFrameRate;
config.rcParams.averageBitRate = this->bitrate; 
```
should be
```
reconfigureParams.reInitEncodeParams.frameRateNum = targetFrameRate;
config.rcParams.averageBitRate = bitrate; 

this->bitrate = bitrate;
this->targetFrameRate = targetFrameRate;
```

I'm still in the process of clarifying legal issues regarding pull requests.  I will let you know once you can start a PR.

In the meantime I suggest you test if everything works as expected now for your use case  (and is fast enough).     

Thanks for your help!

**Comment by hoene** [comment]
Tests are working :-)
