### ISSUE TITLE
Encoding profileGUID 

### ISSUE THREAD

**Issue by benjha** [NVIDIA/NvPipe#27]
Hi Tim, 

I noted NvPipe does not "touch" the encoder profileGUID. Allowing the user to setting it up can be useful for web-based clients since  media source extensions need profile specification.

What is the encoder profileGUID NvPipe is using for H.264 ?

Thanks,

Benjamin

**Comment by tbiedert** [comment]
Hi Benjamin,

thanks for reaching out; this is a good question! 

While NvPipe sets the **preset** to `NV_ENC_PRESET_LOW_LATENCY_HQ_GUID`, it does not touch the **profile**. This means that the profile will be automatically selected by the encoder.

You can manually override the profile in the `Encoder::recreate` method. It's the `profileGUID` property of `NV_ENC_CONFIG encodeConfig`.

The available profiles are defined in `nvEncodeAPI.h`, just search for `NV_ENC_H264_PROFILE_BASELINE_GUID` for instance.

Hope that helps! 

Best,
Tim
