### ISSUE TITLE
Makefiles generated by cmake can't find the nvcuvid libraries by default

### ISSUE THREAD

**Issue by aakshintala** [NVIDIA/NvPipe#28]
Turns out the video-codec-sdk libraries are distributed with the driver and not CUDA. 
Sigh... Nvidia...
The link commands generated by CMake weren't automatically including the correct library search path.
I got around this by adding -L/usr/lib/nvidia-396 (on a Ubuntu system) to each generated link.txt (in CMakeFiles/NvPipe.dir etc). 

I don't really understand CMake or I'd send a PR, but is there some way for you to include the nvidia driver path automatically in the generated compiler commands?

**Comment by tbiedert** [comment]
Hi, thanks for reaching out!

You can add the library search path via the LDFLAGS environment variable when running CMake for the first time:   https://cmake.org/cmake/help/latest/envvar/LDFLAGS.html

That custom driver library path is specific to the Ubuntu packaged driver. I’ve never experienced this with the run file driver from the website.

Best,
Tim
