### ISSUE TITLE
Current version does not build

### ISSUE THREAD

**Issue by hoene** [NVIDIA/NvPipe#29]
On Ubuntu 14.04, I get the message
/lhome/chhoene/github/NvPipe/src/NvPipe.cu(75): error: class "cudaPointerAttributes" has no member "type"

**Comment by aakshintala** [comment]
You're probably building against CUDA 9.2 or earlier.
Change type to memoryType 
memoryType is deprecated as of CUDA 10.0, however.
see https://docs.nvidia.com/cuda/cuda-runtime-api/structcudaPointerAttributes.html#structcudaPointerAttributes

**Comment by tbiedert** [comment]
Thanks for pointing this out!
Should be fixed in d024a962b2cb88cc4b63a0f19bf5224c41d9169d.
