### ISSUE TITLE
Decoder hangs at cuvidMapVideoFrame for a lone time

### ISSUE THREAD

**Issue by Luyang1125** [NVIDIA/NvPipe#3]
Hi,

I currently have a question about the decoding part. I run the code on my Titan X and realize the decoding part takes more than 10ms to decode one frame. So I go check the decode.c line by line. I found that the code will hang at cuvidMapVideoFrame() for around 8ms, which doesn't make sense to me. Do you have any idea to fix this problem? Thanks!

**Comment by tbiedert** [comment]
Hi, sorry for the delayed response and thanks for the inquiry!

The exact timings of the decode depend on the available hardware, software version and frame size, so it's a bit hard to judge if this is to be expected or not.  At what resolution are you decoding? Have you also measured the encoding part for comparison?  Additionally, some information about your setup would be helpful, e.g., OS/CUDA/driver version.

Please note that NvPipe acts as a lightweight **synchronous convenience layer** around the Video Codec SDK and doesn't offer all high-performance capabilities. If you're looking for ultimate decode performance, you may want to consider using NvCodec directly.

Best,
Tim
