### ISSUE TITLE
Provide example for SLI support?

### ISSUE THREAD

**Issue by iamrohit1** [NVIDIA/NvPipe#31]
Hey,

Can I get an example on how to use NVPIPE with SLI support? 

My code right now:

```
if(numEncodersInUse < 2)                                           //first device 
	cudaError_t status = cudaSetDevice(0); 
else                                                               //second device
	cudaError_t status = cudaSetDevice(1); 

if (status  != cudaSuccess)
	return -1;
nvps[id] = nvpipe_create_encoder(NVPIPE_H264_NV, quality);

if(nvp[id] != NULL)
	numEncodersInUse ++;
```
I get two devices using `cudaGetDeviceCount`. 
I can set first **or** second device and use two encoders without any problem.
But, when I start three, I get Access Violation error in nvpipe.dll.

Any thoughts?

Thanks in advance.

**Comment by tbiedert** [comment]
Hi,

I strongly suggest using differrent threads for multiple concurrent NvPipe sessions.  So for each worker thread, first set the device and initialize the CUDA context, then create the encoder. You could use a queue to push data into the worker thread.

NvPipe internally assumes that the device and CUDA context do not change. The encoder/decoder instance is not some complete context in that sense, but only used for resource/memory management.

If you’re adventurous, try compiling NvPipe in debug mode and running your application in the debugger. This way you might get more insight into where exactly the access violation happens.

Btw, this looks like an older version of NvPipe, is that right?   Maybe give the current version a try.

Hope that helps!
Tim

**Comment by iamrohit1** [comment]
[https://devtalk.nvidia.com/default/topic/1010992/general-discussion/quadro-vs-geforce-for-parallel-encoding/](https://devtalk.nvidia.com/default/topic/1010992/general-discussion/quadro-vs-geforce-for-parallel-encoding/)

Basically, the encoder limit is set at API level, so there is **no way** of using 4 encoders even if you have SLI.

Thanks for the help Tim! 
-Rohit

**Comment by tbiedert** [comment]
Yes, this is absolutely correct. 

For what it’s worth, you don’t have this limitation with Quadro cards, though.

**Comment by iamrohit1** [comment]
Yes,
I tried with Quadro M4000 and it works like a charm.
