### ISSUE TITLE
Client video output lags behind after upgrade to new NvPipe

### ISSUE THREAD

**Issue by renewagner** [NVIDIA/NvPipe#32]
Hi all,

I recently had to upgrade to CUDA 9.1 (due to a segfault in NVCC; *sigh*) and thus also had to migrate to the CUDA 9 rewrite of NvPipe (78d96afc7636720835d78509347ba8216379e16f). My setup consists of a server that encodes RGBA frames using NvPipe and sends H264 encoded frames to a visualization client that does the decoding using FFMPEG. This was working fine with CUDA 8.0 and the old NvPipe.

After the upgrade to the new NvPipe (and converting my code to the new API) the client output lags behind by about a frame. The first frame is encoded on the server, the client receives a video packet, passes it to FFMPEG but the frame callback (for decoded frames) is only called after the second video packet has arrived and been passed to FFMPEG.

Is there any way to restore the old behavior?

Cheers,

Rene

**Comment by tbiedert** [comment]
Hi, thanks for asking!

Please try adding the following byte sequence to the encoded bitstream after each frame:

```
// This NAL signals the end of a packet; 
// you might semi-correctly think of this as an H.264 frame boundary.

uint8_t* nal = ((uint8_t*) /* end of frame */)
nal[0] = nal[1] = 0;
nal[2] = 1;
nal[3] = 9;
nal[4] = nal[5] = nal[6] = 0;
nal[7] = 1;
nal[8] = 9;
nal[9] = 0;
```
Hope this helps,
Tim

**Comment by renewagner** [comment]
Hi Tim,

thanks for the quick response! I can confirm that appending the NAL sequence fixes the problem for me! Thanks a lot! May I assume that the code snippet is under the same license as NvPipe?

Cheers,

Rene

**Comment by tbiedert** [comment]
Great! 
Yes, please feel free to use it. It's in fact copied from the old NvPipe encoder code. 

Best,
Tim
