### ISSUE TITLE
Does NvPipe support TX2 & AGX XAVIER 

### ISSUE THREAD

**Issue by garybruckheimer** [NVIDIA/NvPipe#33]
Is this only for Desktop GPU´s or does it work with TX2 and Jetson Xavier?

Thanks for any answer.

**Comment by tbiedert** [comment]
Thanks for reaching out!

NvPipe does not support the Jetson platform, on which the video hardware should be accessed through the [NvMedia API](https://docs.nvidia.com/drive/nvvib_docs/NVIDIA%20DRIVE%20Linux%20SDK%20Development%20Guide/baggage/group__nvmedia__top.html).

Tim

**Comment by sjdrc** [comment]
Hey, just to clarify, the NvMedia API is for the Drive PX2 platform.

On Jetson platforms including TX2, [TegraMM API](https://docs.nvidia.com/jetson/l4t-multimedia/index.html) should be used.
