### ISSUE TITLE
Porting to new NvPipe: Video quality/bitrate parameter

### ISSUE THREAD

**Issue by renewagner** [NVIDIA/NvPipe#34]
Hi all,

can you clarify the semantics of the bitrate parameter of the new (post CUDA 9) NvPipe compared with the old one? Using the same parameter value is the H264 video quality expected to stay the same after decoding? I previously used the following:

```c++
const size_t f_m = 5;
const uint64_t bitrate = width*height * fps*f_m*0.07; // Kush gauge
```

With the new NvPipe, this gives visually worse results than before, i.e. the decoded image is blurrier and exhibits more artifacts.

Cheers,

Rene

**Comment by tbiedert** [comment]
Hi,

you always have to consider bitrate in conjunction with a specific target frame rate, at which the encoded bitstream should equal the given bitrate. Example:  Assume you encode your video for 16 Mbps @ 60 Hz. If you now transmit the frames at only 30 Hz, it will only require 8 Mbps of network bandwidth.

The old NvPipe internally forwarded a hardcoded frame rate of 30 Hz to the encoder, whereas the new interface allows to explicitly set the target frame rate.

So if you don't change your bitrate computation based on Kush gauge, just pass a target frame rate of 30 in the new interface. This should actually produce similar results as before.

Best,
Tim
