### ISSUE TITLE
Interaction with libNPP (might be off topic)

### ISSUE THREAD

**Issue by aakshintala** [NVIDIA/NvPipe#37]
This isn't an issue with NvPipe as such. I've found NvPipe (and some of the NvCodec Utils) quite useful. Thank you for open sourcing your work!

I'm writing an application that decodes, resizes_and_letterboxes (to the size expected by an object classification DNN running on a seperate GPU), and then re-encodes a given video stream on the GPU.

Once the frame is decoded by NvPipe (output format: NVPIPE_UINT8), the device pointer is passed to the following functions from libNPP:
nppiResize_8u_C4R (to resize)
nppiCopyConstBorder_8u_C4R (to letterbox)

The output frame resizing isn't working as expected: the image is entirely in the green spectrum and restricted to the top 1/3 of the frame. Any idea what could be going on? Intuition tells me this is likely a mismatch in formats...

Tried using NVPIPE_RGBA but the libNPP resize functions then proceeded to mess up the frame entirely resulting in mostly noise in the image... 

What color format is the frame output by the decoder in? NV12/YUV420?
Any chance you know what format libNPP expects?

Apologies on the slightly off-topic question, but I couldn't find an answer to this anywhere else, and I'm hoping to be able to leverage your expertise with NVDEC (and hopefully libNPP)...

**Comment by tbiedert** [comment]
Hey, thanks for reaching out! Interesting setup!

I'm not experienced with libNPP, so I'm afraid I'm of no help here in that regard. However, this might be an issue with NvPipe or its usage after all.

So apparently you already have an encoded video as input and want to decode it using NvPipe. In this case, the NVPIPE_UINT8 format is probably not doing what you expect. (What do you expect? :-) )

Please understand that NvPipe was mostly not developed for interop with other encoders/decoders in mind. It should work and does work for RGB inputs/outputs, however the UINT formats are actually NvPipe-specific and target greyscale image compression, such as detector data. 

Depending on the bit depth the unsigned int format is internally converted to/from NV12 differently. The UINT8 case is the least problematic, as it simply copies the UINT8 greyscale data to/from the Y channel. In case of UINT16 for instance, the image width is effectively doubled, where the left half contains the higher 8 bits in the Y channel, the right half the lower 8 bits in the Y channel. In any case of UINT, the UV channels are zeroed and not used. The motivation for this hoop jumping is to achieve better spatial compressibility.

I just checked the documentation of the `nppiResize_8u_C4R` call, which states "4 channel 8-bit unsigned image resize". So this obviously fails with the NVPIPE_UINT8 greyscale format. 

I'm intrigued that the NVPIPE_RGBA format does not work here. As a sanity check, you might want to write NvPipe's RGBA output to an image file before passing it to nppiResize.

Please note that there recently was some confusion with the RGBA format, as internally the encoder/decoder is effectively interpreting the data as BGRA. Thus, as a short term clarification I have renamed the format to NVPIPE_BGRA. I've put a real RGBA format on my TODO list, though.  
The swizzling of channels does not really matter when you're using NvPipe on both sides (modulo some RGB<->YUV weighted conversion artifacts), however will produce swapped color channels when interop'ing with other encoders/decoders.

Hope that helps!
Tim

**Comment by aakshintala** [comment]
Thanks for the detailed feedback Tim!

I figured out that the uint* formats were grayscale when looking through the NvPipe code after posting here. Should have posted an update to save you extra work of explaining it. Apologies.

Looks like I really just need NvPipe to export the NV12 image directly without changing format...
I can then use https://github.com/dusty-nv/jetson-utils/blob/master/cuda/cudaYUV-NV12.cu 
and https://github.com/dusty-nv/jetson-utils/blob/master/cuda/cudaResize.cu to do the format conversion, and resizing (although I'll probably have to write a kernel to letterbox the image)...
Main reason for this is that the DNN framework I want to move the data to (https://pjreddie.com/darknet/yolo/) wants the data to be in floating point RBG...

I added NVPIPE_NV12 to the format enum, and added code to copy from the decode buffer to the device pointer back passed by the caller (and vice versa in the encoder). However, I seem to be copying either too little or too much data, and I can't figure out the size of the buffer to copy... 
this->decoder->GetDeviceFramePitch()*height doesn't seem to be right because I end up with a re-encoded video that looks like this:
![screen shot 2018-10-26 at 9 49 01 pm](https://user-images.githubusercontent.com/748697/47598389-faa8e900-d968-11e8-89cb-53eed8aa20c9.png)

I read more about the NV12 format (never dealt with image or video before this; I primarily do compilers and OSes...) and thought the correct amount might be GetDeviceFramePitch()*height*2 (8bits for Y and 8bits for UV), but the memcpy (from decoder buffer to caller buffer) throws Error 11: invalid argument (which probably means I've tried to copy too much data...

If you could take a look, I'd be much obliged: https://github.com/aakshintala/darknet/blob/0dadb23a91ecc8f5d56c7c54562b759adc314ff9/live-streaming/nvpipe/src/NvPipe.cu#L744

**Comment by aakshintala** [comment]
Tried DeviceFramePitch*Height*1.5 (that seems to be correct multiple from the YUV2RGB code), but I still end up with garbled output.. 

![screen shot 2018-10-26 at 10 31 46 pm](https://user-images.githubusercontent.com/748697/47598752-f4b60680-d96e-11e8-9d2e-718acd1fa460.png)

Thanks for your time BTW!

**Comment by aakshintala** [comment]
Finally figured it out. The NvEncoder input buffer had a larger pitch than the input buffer I was copying from... That was causing things to get messed up.

Would you like me to submit a PR adding NV12 as a supported decode/encode format?

**Comment by tbiedert** [comment]
Hey, good to hear you solved the pitch issue! 

Thanks for offering a PR! I'm afraid, for the time being I have to respectfully decline due to legal reasons. In case there is more demand for it, I'll quickly add it myself.

Nevertheless, I'm sure this thread will be helpful in case someone else runs into nv12 related format issues.

Thanks,
Tim
