### ISSUE TITLE
Stream encoded frame with ffmpeg - no existing PPS 0 referenced

### ISSUE THREAD

**Issue by danneboom** [NVIDIA/NvPipe#39]
Hello,

at first many thanks to this awesome project!
I want to encode frames from camera and stream them via RTP using FFmpeg. I adapted my code from the FFmpegStreamer class from src/NvCodec/Utils (code below).

When I first start ffplay with
``` ffplay test.sdp -protocol_whitelist file,udp,rtp ```
and *then* immediatly start the stream, it works, and I see the dummy image. The output of ffplay is then
```bash
Input #0, sdp, from 'test.sdp':    0KB vq=    0KB sq=    0B f=0/0   
  Metadata:
    title           : No Name
  Duration: N/A, start: 0.199333, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480 [SAR 1:1 DAR 4:3], 30 fps, 30 tbr, 90k tbn, 60 tbc
   5.06 M-V: -0.061 fd=   6 aq=    0KB vq=    0KB sq=    0B f=1/1  
```

But when I *first* start the streaming, or wait too long, I get the following (repeating) output from ffplay:
```sh
[h264 @ 0x7f3c6c007e80] decode_slice_header error
[h264 @ 0x7f3c6c007e80] non-existing PPS 0 referenced
[h264 @ 0x7f3c6c007e80] decode_slice_header error
[h264 @ 0x7f3c6c007e80] non-existing PPS 0 referenced
[h264 @ 0x7f3c6c007e80] decode_slice_header error
[h264 @ 0x7f3c6c007e80] non-existing PPS 0 referenced
[h264 @ 0x7f3c6c007e80] decode_slice_header error
[h264 @ 0x7f3c6c007e80] no frame!
[h264 @ 0x7f3c6c007e80] non-existing PPS 0 referenced    0B f=0/0   
    Last message repeated 1 times
```

It seems like I dont set the frame keywords correctly ([see also](https://stackoverflow.com/questions/15005436/errors-when-decode-h-264-frames-using-ffmpeg)). Do you have any idea how to fix this, how to extract the information out of the encoder? Is it related to this line
```c++
 if(!memcmp(compressed.data(), "\x00\x00\x00\x01\x67", 5)) {
    pkt->flags |= AV_PKT_FLAG_KEY;
}
```
I know its not necessarily an issue of NvPipe, but the FFmpegStreamer is from this project and it is related to the output of the encoder. Might be related to #32.
Another question: Does your NvPipe Encoder use a buffer like the nvidia codec sdk samples? Or does it immediately produce an output for every input frame?

Thank you very much in advance.

My code:

```c++
// uses dummy frame like the example file.cpp 

// init encoder
AVPacket *pkt = new AVPacket();
NvPipe* encoder = NvPipe_CreateEncoder(NVPIPE_BGRA32, codec, NVPIPE_LOSSY, bitrateMbps * 1000 * 1000, targetFPS);
if (!encoder)
     std::cerr << "Failed to create encoder: " << NvPipe_GetError(NULL) << std::endl;

// init stream output
std::string str = "rtp://127.0.0.1:49990";
AVOutputFormat *output_format = nullptr; /**< Context specifying output format*/
AVFormatContext *output_format_ctx = nullptr; /**< Context specifying output format context*/
AVStream* stream; /**< The video stream informations*/
output_format = av_guess_format("rtp", nullptr, nullptr);
output_format_ctx = avformat_alloc_context();
avformat_alloc_output_context2(&output_format_ctx, output_format, output_format->name, str.c_str());

// open output url
if (!(output_format->flags & AVFMT_NOFILE)){
     ret = avio_open(&output_format_ctx->pb, str.c_str(), AVIO_FLAG_WRITE);
     if (ret < 0) {
         qFatal("Could not open url");
     }
}

output_format_ctx->oformat = output_format;
output_format->video_codec = AV_CODEC_ID_H264;

stream  = avformat_new_stream(output_format_ctx,nullptr);
stream->id = 0;
stream->codecpar->codec_id = AV_CODEC_ID_H264;
stream->codecpar->codec_type = AVMEDIA_TYPE_VIDEO;
stream->codecpar->width = mData->width_out;
stream->codecpar->height = mData->height_out;
stream->time_base.den = 1;
stream->time_base.num = 30; // 30fps


/* Write the header */
ret = avformat_write_header(output_format_ctx, nullptr);
if (ret != AVSTREAM_INIT_IN_WRITE_HEADER){
    qFatal("Header could not be written correctly!");
}


// encoding and streaming - this runs in a loop
const uint32_t width = 640;
const uint32_t height = 480;

std::vector<uint8_t> rgba(width * height * 4);
std::vector<uint8_t> compressed(rgba.size());

// Encoding
// Construct dummy frame
for (uint32_t y = 0; y < height; ++y)
    for (uint32_t x = 0; x < width; ++x)
        rgba[4 * (y * width + x) + 1] = (255.0f * x* y) / (width * height) * (y % 100 < 50);

uint64_t size = NvPipe_Encode(encoder, rgba.data(), width * 4, compressed.data(), compressed.size(), width, height, false);

if (0 == size)
    std::cerr << "Encode error: " << NvPipe_GetError(encoder) << std::endl;

av_init_packet(pkt);
pkt->data = compressed.data();
pkt->size = size;
pkt->pts = frameCnt;

if(!memcmp(compressed.data(), "\x00\x00\x00\x01\x67", 5)) {
    pkt->flags |= AV_PKT_FLAG_KEY;
}

//stream
fflush(stdout);

// Write the compressed frame into the output
pkt->pts = av_rescale_q(mData->frameCnt_out, AVRational {1, 30}, stream->time_base);
pkt->dts = pkt->pts;
pkt->stream_index = stream->index;

/* Write the data on the packet to the output format  */
//int ret = av_interleaved_write_frame(output_format_ctx, pkt);
int ret = av_write_frame(output_format_ctx, pkt);
av_write_frame(output_format_ctx, NULL);

if (ret < 0) {
    qDebug() << "FFMPEG: Error while writing video frame";
}

/* Reset the packet */
av_packet_unref(pkt); 
```

The .sdp file to open the stream with ffplay looks like this:
```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 58.18.101
m=video 49990 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
```

Edit: I also get this ffplay output and blocking:
```
[h264 @ 0x7f78e0049700] concealing 280 DC, 280 AC, 280 MV errors in P frame
[h264 @ 0x7f78e0264a40] concealing 280 DC, 280 AC, 280 MV errors in P frame
[h264 @ 0x7f78e0049700] Invalid NAL unit 5, skipping.    0B f=1/1   
[h264 @ 0x7f78e026b400] concealing 280 DC, 280 AC, 280 MV errors in P frame
[h264 @ 0x7f78e0049700] Invalid NAL unit 5, skipping.    0B f=1/1  
```

Some of this blocking artefacts are getting very heavy for some images... (Images are screenshots)
![original](https://user-images.githubusercontent.com/20741239/48627068-e4b0a600-e9b3-11e8-9d08-95c2ae8c3785.png)
![compressed](https://user-images.githubusercontent.com/20741239/48627067-e4b0a600-e9b3-11e8-89c7-1a49ae4a305d.png)

**Comment by tbiedert** [comment]
Hi,

the aim of NvPipe is to produce direct compressed output for every single frame. If you encounter a scenario or configuration where this is not the case, please let me know.

The NvCodec package is just copied from Video Codec SDK, which is the official product in this case. Please check out the corresponding [forum](https://devtalk.nvidia.com/default/board/244/) regarding your question about the FFmpeg streamer.

Thanks,
Tim

**Comment by danneboom** [comment]
Thanks for your response! But does the NvPipe write any metadata to the output or not?

**Comment by tbiedert** [comment]
NvPipe does not write any additional metadata. It just forwards the output of NvCodec.

**Comment by danneboom** [comment]
Well, as you can see [here](https://devtalk.nvidia.com/default/topic/1044394/video-codec-sdk/how-can-i-make-h264-p-frame-contain-pps-header/), one can set parameters to nvcodec. Are there any of these (NV_ENC_PIC_FLAG_OUTPUT_SPSPPS | NV_ENC_PIC_FLAG_FORCEIDR) set?

**Comment by tbiedert** [comment]
Those two are set if you force an I-frame, see [here](https://github.com/NVIDIA/NvPipe/blob/56a6e502b126b9f65174cbd9b77120efe5d314d3/src/NvPipe.cu#L624).
