### ISSUE TITLE
(c)cmake error - file failed to rename

### ISSUE THREAD

**Issue by tpruzina** [NVIDIA/NvPipe#4]
During subsequent runs with (c)cmake (3.6.0) , I get this error:

```
CMake Error at CMakeLists.txt:44 (file):
  file COPY cannot find "/home/tomas/projects/NvPipe/nvEncodeAPI-v5.h".

CMake Error at CMakeLists.txt:50 (file):
  file RENAME failed to rename

    /home/tomas/projects/NvPipe/nvEncodeAPI-v5.h
  to
    /home/tomas/projects/NvPipe/nvEncodeAPI.h

  because: No such file or directory
```

It would seem that initial run of cmake renames the file already, e.g. causing subsequent runs fail.
Seems to have been introduced in 5dc7ef25 .

**Comment by tbiedert** [comment]
Hi, thanks for the feedback!

It looks like you have done an in-source build, which is [not recommended](https://cmake.org/Wiki/CMake_FAQ#Out-of-source_build_trees).  

Please create a separate build directory, e.g. in Ubuntu 17.04:

```
git clone https://github.com/NVIDIA/NvPipe.git
cd NvPipe
mkdir build
cd build
CC=gcc-5 CXX=g++-5 cmake -DCMAKE_C_FLAGS=-L/usr/lib/nvidia-375 -DEGL_LIBRARY=/usr/lib/nvidia-375/libEGL.so -DEGL_opengl_LIBRARY=/usr/lib/nvidia-375/libOpenGL.so ..
make -j
```

Best,
Tim

**Comment by tpruzina** [comment]
Thanks, tried out of tree build afterwards but the root tree of the repo was dirty already.
