### ISSUE TITLE
out of memory while trying to create encoder

### ISSUE THREAD

**Issue by sylvain121** [NVIDIA/NvPipe#40]
Hi all, 

I have an old GTX 750 with 1Go VRAM.
If I run a game and after try to start an Encoder , I have a " out of memory" because the game all the available VRAM.
Is there a way to force the GPU to free required memory to start an encoder ?

Thank's for your help
sylvain

**Comment by tbiedert** [comment]
Hi! Not sure I'm getting this right, but wouldn't freeing device memory that is currently used by the game sort of break the game? :-)

If you want to perform both rendering and encoding on a single device, I strongly suggest a card with more memory capacity.

Best,
Tim
