### ISSUE TITLE
Trying to create multiple encoder objects

### ISSUE THREAD

**Issue by pdrak** [NVIDIA/NvPipe#42]
I work on a scenario where i need to encode 4 streams of video concurrently (4 different cameras for the same scene). So i try to create 4 encoder objects using the NvPipe_CreateEncoder function. After the first couple is created, the 3rd and 4th fail to be created giving an error with code 10. I work on a gtx 1070. Is it related to my hardware (i.e. the number of engines my gpu has) or NvPipe can not work in this manner because of objects sharing some state? Thank you in advance.

**Comment by tbiedert** [comment]
I'm afraid your GPU only supports two concurrent encode sessions:  https://developer.nvidia.com/video-encode-decode-gpu-support-matrix#Encoder
