### ISSUE TITLE
support YUV inputs

### ISSUE THREAD

**Issue by mcginty** [NVIDIA/NvPipe#43]
Forgive me if I'm mistaken since I've only skimmed the NvPipe source, but it looks like it currently converts from RGB to YUV internally, and it would be really helpful if I could just use YUV directly.

Many webcams on the market only provide YUV sources directly, for example.

**Comment by tbiedert** [comment]
The underlying nvEncodeAPI supports various YUV formats as input, see [here](https://github.com/NVIDIA/NvPipe/blob/master/src/NvCodec/NvEncoder/nvEncodeAPI.h#L331).

You can easily adjust NvPipe to your needs by declaring a new format enum and forwarding the YUV data as is currently done with the RGB data, just search for `NVPIPE_BGRA32` to find the few relevant places.
