### ISSUE TITLE
Error in NvPipe_CreateEncoder with NV_ENC_H264_PROFILE_BASELINE_GUID

### ISSUE THREAD

**Issue by AndreFrelicot** [NVIDIA/NvPipe#46]
Hello,
I need to encode with the baseline profile
so I changed the presetGUID in NvPipe.cu to  NV_ENC_H264_PROFILE_BASELINE_GUID 
(https://github.com/NVIDIA/NvPipe/blob/4f410170332503eccd59d9e3c29ae600353ca556/src/NvPipe.cu#L578)

But the NvPipe_CreateEncoder returns an error 8 (NV_ENC_ERR_INVALID_PARAM).
It works with the default profile, I also changed the format (NVPIPE_BGRA32, NVPIPE_UINT8, NVPIPE_UINT16 etc), no result.

System :
Cuda compilation tools, release 10.0, V10.0.130
Linux Ubuntu 18

`Tue Jan 15 15:28:58 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.57                 Driver Version: 410.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   37C    P8     5W /  N/A |    103MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+`

**Comment by tbiedert** [comment]
Hello! Could you be a bit more specific please?
What exactly did you try? And what's the error?

**Comment by AndreFrelicot** [comment]
Sorry send the issue too quickly, I updated it.
thank you

André

**Comment by AndreFrelicot** [comment]
![image](https://user-images.githubusercontent.com/2123744/51186917-04444c00-18db-11e9-841a-10068af5be29.png)

**Comment by AndreFrelicot** [comment]
![image](https://user-images.githubusercontent.com/2123744/51186998-2d64dc80-18db-11e9-804f-4d068e41aff6.png)

**Comment by tbiedert** [comment]
Apparently you are confusing encoder presets with H.264 profiles.
Try setting `encodeConfig.profileGUID = NV_ENC_H264_PROFILE_BASELINE_GUID;`. It's currently not actively set in NvPipe, thus using `NV_ENC_CODEC_PROFILE_AUTOSELECT_GUID` as default.

You can check the `nvEncodeAPI.h` header for enumerations of all profiles and presets.

Hope that helps!

**Comment by AndreFrelicot** [comment]
Thank you it works !

Still the frames are not decoded in JS with Broadway.js (I'm trying to stream with websockets) but that's a different matter.

**Comment by AndreFrelicot** [comment]
Thank you for the info

I fixed the decoding in broadway by setting the forceIFrame to true in the NvPipe_Encode call. :)
