### ISSUE TITLE
OpenGL Multiple Threads for Rendering and Encoding

### ISSUE THREAD

**Issue by h0ax-ki1l3r** [NVIDIA/NvPipe#47]
Hi,

I have a multi-threaded scenario for video encoding where:

Thread 1: 
- creates OpenGL Context
- creates/binds a bunch of FBO/Textures
- reads a bunch of frames
- starts rendering every frame into a texture

Thread 2
- reads texture, and uses `NvPipe_EncodeTexture()` API to encode the frame

However this does not seem to work. I have limited knowledge in OpenGL, and after going through numerous online articles is related to the OpenGL context not being available in Thread 2. Can someone please help me on how to proceed? Ideally for performance, I wanted one thread to render while other to encode.

Thanks.

**Comment by h0ax-ki1l3r** [comment]
Thanks for the pointers, this certainly helps me take next steps!

Two quick questions:

1. For the OpenGL approach, when you say "sharing data with render context" how do you do such sharing? and you suggest using two textures, I am already creating a bunch of textures at `init` (which follows an object pool pattern) where the rendering thread acquires a pair of `texture` and `FBO` objects from the pool, while the encoding thread after encoding releases them back to the pool for subsequent uses. 

2. Comparing CUDA approach with the OpenGL approach, would you be able to know which one would be faster and/or memory efficient?

Thanks,
Arvind

**Comment by tbiedert** [comment]
For the context sharing you need to check the docs of the window framework you are using. The OpenGL context creation is the platform-specific part. Typically there is some way to create a new context, and give an existing context as parameter to be used for sharing resources.

I wouldn’t expect much difference between the two approaches. The CUDA approach is probably the more explicit one, where you have more control but need to code more (but you can use NvPipe’s texture encoding function as reference). 

For starters, I’d suggest trying the OpenGL route first. I haven’t tried that shared context scenario, though. 

If you need the maximum of control and encode performance, you may want to look into using the NvEncode API directly (either the low level interface or the NvCodec wrappers that NvPipe is based on).

Tim

**Comment by h0ax-ki1l3r** [comment]
Thanks for the info. I'll try the CUDA approach as I have a reference point :)

**Comment by tbiedert** [comment]
Avoiding the memory copy is not a question of the CUDA API but the encode API. Since NvPipe is based on the NvCodec convenience wrapper from Video Codec SDK, it uses the set of input buffers provided by it. You might be able to get rid of that copy by using the low level NVENC API (see NvEncodeAPI.h).

However, that copy operation is typically not the bottleneck.  Your goal should be to keep the hardware fully utilized, and your approach of having concurrent render/encode threads is the right way. That copy operation is rather negligible if you efficiently overlap your rendering and encoding.

**Comment by Ziriax** [comment]
I have some related questions:

* Does this copy operation happen purely on the GPU, or is it first transferred to the CPU and back to NVENC hardware?

* I thought NVENC was using dedicated hardware, not putting any load on rendering, is that correct?

* Does NVENC share the same memory with the GPU, or does it have its own private memory?

**Comment by tbiedert** [comment]
That copy operation happens on the device, there is no host transfer involved (which would be a perf hit).

The encoders (and decoders) are dedicated hardware that can overlap with rendering and compute work. They use the same device memory.

**Comment by Ziriax** [comment]
@tbiedert That is really amazing, exactly what we need.

I'm trying to convert Microsoft's 3D streaming toolkit  to an easy to use .NET Core library. The former already uses NVEnc but using an old version of Google's webrtc that is now mostly obsolete, and furthermore it first copies to CPU memory, then back to the GPU

Our goal is use NVEnc hardware encoding together with webrtc, without copying anything to the CPU, to get ultra low latency, overlapped rendering of GLTF models.

https://github.com/WonderMediaProductions/webrtc-dotnet-core
