### ISSUE TITLE
Making under Code::Blocks

### ISSUE THREAD

**Issue by ProjectRobal** [NVIDIA/NvPipe#49]
I used cmake to make NvPipe works under Code::Blocks. After making a NvPipe in cmake it created  code::blocks project file when I open project and tried to compile it. It shows me errors:

`CMakeFiles\NvPipe.dir\build.make|69|recipe for target 'CMakeFiles/NvPipe.dir/src/NvCodec/Utils/NvPipe_generated_ColorSpace.cu.obj' failed|
CMakeFiles\Makefile2|145|recipe for target 'CMakeFiles/NvPipe.dir/all' failed|
C:\Users\admin\Downloads\NvPipe-master\Makefile|128|recipe for target 'all' failed|
`

**Comment by tbiedert** [comment]
Hi, thanks for reaching out!

Can you please post the full output you get?  

Some info on your setup would also be helpful (OS, driver, ..).

Thanks!

**Comment by ProjectRobal** [comment]
I am using Windows 10 
with CUDA 9.0
cmake 3.13.2
compiler is 64bits MinGW


There show me error:

![err](https://user-images.githubusercontent.com/46270898/51927963-1a7efb80-23f5-11e9-8243-bf157e142b83.jpg)

**Comment by tbiedert** [comment]
I don't have any experience with Code::Blocks, but it seems like "Build messages" tries to summarize important messages. Can you please check if "Build log" contains the full build output? 

Thanks,
Tim

**Comment by ProjectRobal** [comment]
Build log shows:


mingw32-make.exe[2]: Leaving directory 'C:/Users/admin/Downloads/NvPipe-master'
CMakeFiles\Makefile2:145: recipe for target 'CMakeFiles/NvPipe.dir/all' failed
mingw32-make.exe[1]: Leaving directory 'C:/Users/admin/Downloads/NvPipe-master'
C:/Users/admin/Downloads/NvPipe-master/Makefile:128: recipe for target 'all' failed

**Comment by tbiedert** [comment]
Thanks!  The relevant error message is: `nvcc fatal : Host compiler targets unsupported OS`.

On Windows, you need to use [a supported version of Visual Studio](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#system-requirements). MinGW is not supported.

Check out Visual Studio community edition. Maybe you can even use the VC compiler in Code::Blocks.

Hope that helps!
Tim
