### ISSUE TITLE
NVENC doesn't initialize with EGL context on Linux

### ISSUE THREAD

**Issue by sasmaster** [NVIDIA/NvPipe#5]
Hi, I didn't find another place to file this bug. I am using Linux Ubuntu 16.04. I decided to try EGL API for OpenGL offscreen context creation. The context is created ok, no errors. But the NVENC fails to init with the error: 

    nvStatus = m_pEncodeAPI->nvEncOpenEncodeSessionEx(&openSessionExParams, &m_hEncoder);

nvStatus = NV_ENC_ERR_UNSUPPORTED_DEVICE.

Do you have an idea why that happens?

EGL init part:

 ```
const EGLint configAttribs[] = {
          EGL_SURFACE_TYPE, EGL_PBUFFER_BIT,
          EGL_BLUE_SIZE, 8,
          EGL_GREEN_SIZE, 8,
          EGL_RED_SIZE, 8,
          EGL_DEPTH_SIZE, 8,
          EGL_RENDERABLE_TYPE, EGL_OPENGL_BIT,
          EGL_NONE
    };

// 1. Initialize EGL
  mEGLDisplay = eglGetDisplay(EGL_DEFAULT_DISPLAY);  
  EGLint major, minor;

  eglCheck(eglInitialize(mEGLDisplay, &major, &minor));
  
  // 2. Select an appropriate configuration
  EGLint numConfigs;
  EGLConfig eglCfg;

  eglCheck(eglChooseConfig(mEGLDisplay, configAttribs, &eglCfg, 1, &numConfigs));
  
  // 3. Create a surface
   
  const EGLint pbufferAttribs[] = {
        EGL_WIDTH, 9,
        EGL_HEIGHT, 9,
        EGL_NONE,
  };
  EGLSurface eglSurf = eglCreatePbufferSurface(mEGLDisplay, eglCfg,  pbufferAttribs);
                                                                                          
  // 4. Bind the API
   eglCheck(eglBindAPI(EGL_OPENGL_API));   

// 5. Create a context and make it current
  const char *extensions = eglQueryString(mEGLDisplay,EGL_EXTENSIONS);
  bool robust_access_ext = ExtensionIsSupported(extensions,"EGL_EXT_create_context_robustness");
  
  EGLint context_attribs[] = {
    EGL_CONTEXT_MAJOR_VERSION,mVersionMajor,
    EGL_CONTEXT_MINOR_VERSION,mVersionMinor,
    EGL_CONTEXT_OPENGL_PROFILE_MASK,EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT,
    EGL_CONTEXT_FLAGS_KHR,
     EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR | 
     EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR ,
      
     EGL_NONE    
    
  };

  mEGLContext = eglCreateContext(mEGLDisplay, eglCfg, EGL_NO_CONTEXT, 
                                       context_attribs); 
   eglCheck(eglMakeCurrent(mEGLDisplay, EGL_NO_SURFACE, EGL_NO_SURFACE, mEGLContext));  
```

**Comment by tbiedert** [comment]
Hi,
looking at your nvEncOpenEncodeSessionEx call, it seems like you're not using NvPipe, but the low level encode API interface? Are you trying to create an encoder with direct OpenGL input (Linux-only support since SDK 8)?

Can you please post some more information on your setup, i.e. hardware and driver version?

Best,
Tim

**Comment by sasmaster** [comment]
That's what I am trying to say :)  I don't use NvPipe. I have my own nvenc
setup.  It all works fine when using GLX context. But after I read in your
website that now it's also possible to create a context with EGL, which is
much simpler and doesn't require pbuffer object at all, I decided to try it
out. I haven't found any e-mail or other means to contact Nvidia regarding
this. That's why I posted it here. Btw, I am running on  384.69 drivers.
Using NVENC 8 .

**Comment by tbiedert** [comment]
Thanks for reaching out! Direct OpenGL input is only available for GLX contexts, I'm afraid. For EGL setups you currently have two options, both involving CUDA/GL interop and using NvEnc with a CUDA device:
(1) Read framebuffer/pixels into PBO (can be done async and combined with double buffering), map PBO to CUdeviceptr using interop and register it as RGBA input in NvEnc
(2) Map color attachment/texture of framebuffer to CUarray using interop, and have a custom CUDA kernel performing manual color space conversion from RGBA to NV12 (YUV with UV interleaved) format. Store NV12 output in pitched linear device memory, which is registered with NvEnc.

For simplicity I recommend going down the (1) road. However, if you're interested in (2), feel free to check out the NvPipe sources, which include an exemplary RGBA/NV12 conversion kernel for linear RGBA input. (Native RGBA input was enabled in Video Codec SDK 6, but NvPipe was supposed to work with SDK 5 as well).

Hope that helps!

**Comment by sasmaster** [comment]
Well, that's what I wanted to know. I have no problem running on glx. Just
wanted to switch to a more compact API. Thanks for the clarification!

**Comment by sasmaster** [comment]
Btw, if we are alre talking about the encoding pipeline I have another
question. I perform rgb to yuv conversion using compute shader. I found no
way to elegantly synchronize the moment when compute shader has finished
and the texture is getting mapped as cuda resources for the encoding
session. Only calling  glFinish () immediately after glDispatchCompute
 causes the CS to finilize its execution. This is bad for GL pipelining. It
would be nice to have a more sophisticated sync mechanism in this case.
 I even asked on SO a question regarding this problem several months ago:
https://stackoverflow.com/questions/37569065/memory-barrier-fails-to-sync-between-compute-stage-and-data-access-by-cuda

**Comment by tbiedert** [comment]
Please post your issue in e.g. the Video Technologies sub forum at NVIDIA Devtalk:  https://devtalk.nvidia.com/default/board/175/video-technologies/

I would probably recommend moving the color conversion to a CUDA kernel, which opens up other synchronization measures such as streams.

**Comment by sasmaster** [comment]
Hi. Has anythin
g changed since the last time ? I mean  is it possible now to use egl context with NVENC on Linux?
