### ISSUE TITLE
NvPipe.NET

### ISSUE THREAD

**Issue by MutterOberin** [NVIDIA/NvPipe#54]
I saw the presentation of NVPipe in Brno. I would love to integrate it into my existing tool, therefore I am wondering if it is possible to wrap it for the use with [OpenTK ](https://github.com/opentk/opentk)/ other .NET based applications.

**Comment by tbiedert** [comment]
Hey, thanks for attending my talk :-)

Currently there are no plans for a C#/.NET interface of NvPipe.  

Do you see any technical reasons why using P/Invoke to load the NvPipe DLL would not work?

**Comment by MutterOberin** [comment]
This is what I meant. I just want to have a small .NET class taking care of the calls to the NvPipe.dll. I can start to look into that but be nice to have a little support. 

Do you have prebuild windows binaries for x86 and x64?

**Comment by tbiedert** [comment]
We currently don't provide prebuilt binaries of NvPipe, so you'll have to compile it yourself. But that's pretty straightforward using Visual Studio's builtin CMake support. I'm using the following `CMakeSettings.json`:
```
{
  "configurations": [
    {
      "name": "x64-Release",
      "generator": "Ninja",
      "configurationType": "Release",
      "inheritEnvironments": [
        "msvc_x64_x64"
      ],
      "buildRoot": "C:\\.build\\NvPipe\\${name}",
      "installRoot": "C:\\.install\\NvPipe\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "GLEW_INCLUDE_DIR",
          "value": "C:\\Development\\Libraries\\glew-2.1.0\\include"
        },
        {
          "name": "GLEW_LIBRARY_RELEASE",
          "value": "C:\\Development\\Libraries\\glew-2.1.0\\lib\\Release\\x64\\glew32.lib"
        }
      ]
    }
  ]
}
```

I'm not a .NET developer, but I can give you technical support on the native NvPipe side.

**Comment by MutterOberin** [comment]
Thanks! That is very nice to know! 

The project will be hosted here: [NvPipe.NET](https://github.com/MutterOberin/NvPipe.NET)

**Comment by Ziriax** [comment]
We have used `NvPipe` (and extended it so it can accept Direct3D11 textures) for our [.NET Core webrtc project](https://github.com/WonderMediaProductions/webrtc-dotnet-core). It is very experimental, but it can already render and transmit H264 from an ASP.NET Core application to a web-page. We didn't expose `NvPipe` functionality yet, only some `webrtc` functions, but it should be trivial to do so. I would like to do so using [CppSharp](https://github.com/mono/CppSharp) however, since manually creating and maintaining wrappers is a real pain.

**Comment by tbiedert** [comment]
I've just pushed an update including Video Codec SDK 9 (5426f6b7fd72d27310b51a00ad439aba15446c50) and some fixes. Note that the signatures have slightly changed, i.e., you now need to specify the initial dimensions of the encoder/decoder when creating them.

Feel free to reopen this issue if necessary.

Thanks!
