### ISSUE TITLE
High memory consumption for decoder

### ISSUE THREAD

**Issue by galano25** [NVIDIA/NvPipe#58]
Hello,
I’m instantiating 8 instances of the H264 decoder to decode 8 streams in parallel. It works great! However it consumes like 3.2GB of CUDA memory. This is a lot. Is there a way to reduce the amount of memory consumed per instance?

I’m using BGRA32 for output to device memory.

Thanks!

**Comment by tbiedert** [comment]
Hi, thanks for reaching out!

Each decoder allocates memory for multiple previous frames for proper temporal reconstruction. This is controlled by the `ulNumDecodeSurfaces` property of the decoder, which is set to `20` for H.264 (see [here](https://github.com/NVIDIA/NvPipe/blob/5426f6b7fd72d27310b51a00ad439aba15446c50/src/Video_Codec_SDK_9.0.20/Samples/NvCodec/NvDecoder/NvDecoder.cpp#L144)).

There threads will give you a little more insight:
- [Bad H264 Image Decoded and Controlled by ulNumDecodeSurfaces](https://devtalk.nvidia.com/default/topic/1037418/bad-h264-image-decoded-and-controlled-by-ulnumdecodesurfaces/)

- [How to calculate appropriate value for CUDA/CUVID's CUVIDDECODECREATEINFO:: ulNumDecodeSurfaces ...](https://devtalk.nvidia.com/default/topic/1030310/how-to-calculate-appropriate-value-for-cuda-cuvids-cuviddecodecreateinfo-ulnumdecodesurfaces-used-in-cuvidcreatedecoder-/)

Depending on your input source, you can try experimenting with lower values.

Hope that helps!
Tim

**Comment by galano25** [comment]
Thank you! I’ll play around with that variable

**Comment by raghs7** [comment]
[INFO ][14:28:58] Video Input Information
        Codec        : H.265/HEVC
        Frame rate   : 30/1 = 30 fps
        Sequence     : Progressive
        Coded size   : [1920, 1088]
        Display area : [0, 0, 1920, 1080]
        Chroma       : YUV 420
        Bit depth    : 8
Video Decoding Params:
        NumOutput_Surfaces : 2
        Num Surfaces : 7
        Crop         : [0, 0, 0, 0]
        Resize       : 1920x1088
        Deinterlace  : Weave

the GPU memory required for For decoding above video is 140MB , this doesn't correlate with memory required
1920*1080*8(bit depth)*1.5 (yuv420)*(7+2) (number of surfaces) = 59MB
