### ISSUE TITLE
NAL type of output bitstream buffer

### ISSUE THREAD

**Issue by sasmaster** [NVIDIA/NvPipe#6]
Hi. I am trying to understand your encoder's logic. Most of the stuff makes sense to me.
But could you please comment on this part?

/* This NAL signals the end of this packet; you might semi-correctly think of
     * this as an h264 frame boundary. */
    ```
uint8_t* nal = ((uint8_t*)obuf) + bitlock.bitstreamSizeInBytes;
    nal[0] = nal[1] = 0;
    nal[2] = 1;
    nal[3] = 9;
    nal[4] = nal[5] = nal[6] = 0;
    nal[7] = 1;
    nal[8] = 9;
    nal[9] = 0;

```
I mean, what type of NALU exactly is that? And is it required for all transfer protocols when streaming via network? 

Thanks!

**Comment by tbiedert** [comment]
Thanks for reaching out! This appears to be legacy code for helping an older cuvid decoder to flush output immediately instead of waiting for subsequent frames. I think you can safely ignore this for your streaming efforts.
