### ISSUE TITLE
Unable to compile NvPipe on Windows 10

### ISSUE THREAD

**Issue by Suhail** [NVIDIA/NvPipe#60]
My goal is to successfully compile NvPipe on Windows 10 to include it in a project.

Here's the error I get:

```
1>------ Skipped Build: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: NvPipe, Configuration: Debug x64 ------
2>LINK : fatal error LNK1104: cannot open file 'C:\Users\digit\Desktop\workspace\NvPipe\build\CMakeFiles\NvPipe.dir\src\Debug\NvPipe_generated_NvPipe.cu.obj'
2>Done building project "NvPipe.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========
```

That file does not exist for me:
```
(py2) suhail@mighty-dev:/mnt/c/Users/digit/Desktop/workspace/NvPipe/build/CMakeFiles/NvPipe.dir/src/Debug$ ls -la
total 0
drwxrwxrwx 1 suhail suhail 4096 Mar 22 15:51 .
drwxrwxrwx 1 suhail suhail 4096 Mar 22 15:51 ..
```

Environment:
```
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.17134 N/A Build 17134
System Type:               x64-based PC
```

Include dirs: http://prntscr.com/n1peud

I began setting up compilation via: `cmake ../ -D NVPIPE_WITH_OPENGL=OFF`

**Comment by Ziriax** [comment]
Are you building with Visual Studio?  

You might want to set your build output settings to diagnostic, and rebuild again.

https://stackoverflow.com/questions/1211841/how-can-i-make-visual-studios-build-be-very-verbose

**Comment by Suhail** [comment]
That was helpful. The solution was to ignore the instructions in the readme & use Visual Studio -> Open with CMake and use these settings: https://github.com/NVIDIA/NvPipe/issues/54#issuecomment-461148079

Add GLEW dirs from vcpkg
