### ISSUE TITLE
Question: Can any h264 decoder decode this?

### ISSUE THREAD

**Issue by PhilAndrew** [NVIDIA/NvPipe#63]
I want to play video encoded from this on the web browser, so I want to decode on the web browser, is this a good idea/possible? like using this https://github.com/131/h264-live-player
Or is it the case only NVPipe can decode its own data encoded with NVPipe?

**Comment by tbiedert** [comment]
Yes, that’s possible, since NvPipe produces/consumes a standard-compliant H.264 stream. 

NvPipe has been successfully used with other decoders such as Broadway [before](https://github.com/NVIDIA/NvPipe/issues/46#issuecomment-454699370).

**Comment by PhilAndrew** [comment]
So happy thankyou!
