### ISSUE TITLE
I can't build Ubuntu

### ISSUE THREAD

**Issue by PhilAndrew** [NVIDIA/NvPipe#64]
I followed the instructions and I can't build, any simple explanation other than I'm not so bright?

philip@ubuntu:~/home/projects/NvPipe/build$ cmake ..
-- The CXX compiler identification is GNU 5.5.0
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.1") 
-- Found EGL: /usr/lib/x86_64-linux-gnu/libEGL.so  
-- Found GLEW: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/philip/home/projects/NvPipe/build
philip@ubuntu:~/home/projects/NvPipe/build$ make
[  6%] Building NVCC (Device) object CMakeFiles/NvPipe.dir/src/Video_Codec_SDK_9.0.20/Samples/Utils/NvPipe_generated_ColorSpace.cu.o
/home/philip/home/projects/NvPipe/src/Video_Codec_SDK_9.0.20/Samples/Utils/ColorSpace.cu(112): error: type name is not allowed
          detected during instantiation of "void Nv12ToColor32<COLOR32>(uint8_t *, int, uint8_t *, int, int, int, int) [with COLOR32=BGRA32]" 
(298): here

/home/philip/home/projects/NvPipe/src/Video_Codec_SDK_9.0.20/Samples/Utils/ColorSpace.cu(112): error: expected a ";"
          detected during instantiation of "void Nv12ToColor32<COLOR32>(uint8_t *, int, uint8_t *, int, int, int, int) [with COLOR32=BGRA32]" 
(298): here
errors continue onwards....

**Comment by tbiedert** [comment]
Hmm, can you maybe try a more recent GCC?  I haven't tried it with GCC 5. I can try to reproduce it next week.

**Comment by PhilAndrew** [comment]
I got it to compile with the latest GCC and perhaps I didn't have gcc on the command line when I ran.... I'm not sure, regardless it compiles now and the only problem is I can't run due to cuda version difference.

Failed to create encoder: Failed to synchronize device (Error 35: CUDA driver version is insufficient for CUDA runtime version)

**Comment by tbiedert** [comment]
Which driver are you running on? (Run `nvidia-smi`)

CMake found CUDA 10.1 according to your log. 
You can check the minimum driver required [here](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility__table-toolkit-driver).

**Comment by PhilAndrew** [comment]
Thanks for being so helpful, it works now. Here is what I learn't.

1. Make sure have latest version of gcc and make sure its available on the command line by typing gcc. Make sure can compile other C / C++ stuff with it.
2. NVida graphics driver must be the right version for CUDA 10.1 and its version match graphics card requirement as NVida says as per your last comment. I had the wrong version installed, had to manually uninstall and install again a new one. That's not so easy to uninstall NVida graphics driver, have to uninstall, reboot, install, reboot, check and it works.
