### ISSUE TITLE
Write to PPM in device memory example?

### ISSUE THREAD

**Issue by mattring** [NVIDIA/NvPipe#69]
After decoding, how would you convert decompressedDevice (void *) to rgba data (uint8_t *) to write to a PPM image in the device memory example?

**Comment by mattring** [comment]
(Resolved) In case anyone is wondering, on the decode side you have to copy the data back to host from memory to print it out: 

cudaMemcpy(rgba.data(), decompressedDevice, rgba.size(), cudaMemcpyDeviceToHost);

**Comment by tbiedert** [comment]
Are you asking for a quicker way to write a PPM from device memory?   What exactly do you want to achieve?

If you‘re writing uncompressed PPMs, the device to host transfer won’t be the bottleneck.

**Comment by bootrino** [comment]
>> You could use async memcpys to copy a frame back to the host while the next frame is already being decoded.

Any chance of adding this to the lib?

More specifically, I'd like to be able to export a frame as a scaled jpeg ideally using on device acceleration such as cuda resize and the NvJpeg library. I've had a serious try but I have to say at this stage it's beyond my skill//experience level right now.  If you were to consider adding frame jpeg scale/export it would be greatly awesome.

**Comment by tbiedert** [comment]
Thanks for the suggestion!  This is unlikely to become a part of NvPipe for now, so I suggest you try the following.

For starters, ignore the rescaling part, but only try to overlap decoding and JPEG output. Check out the following example:   https://docs.nvidia.com/cuda/nvjpeg/index.html#nvjpeg-encode-examples

It uses CUDA streams, so you could easily get started with a single thread and already achieve some overlap, i.e., NvPipe uses the default stream, whereas nvJPEG uses a separate CUDA stream.

A basic loop could look like this:
```
while (more frames)
{
    // Decompress next frame via NvPipe to device memory
    NvPipe_Decode(...) // uses default stream

    // Wait for previous JPEG encoding to finish
    nvjpegEncodeRetrieveBitstream(..., stream)
    cudaStreamSynchronize(stream);
    // ...

    // Do something with encoded JPEG data (e.g., save to disk; 
    // ideally save to some buffer, and another thread writes to disk 
    // async so the loop doesn't block)
    // ...

    // Submit rescaling to same stream that nvJPEG uses
    myScalingKernel<<..., stream>>> (...) ;

    // Submit JPEG encoding of next frame from this iteration
    nvjpegEncodeImage(..., stream);
}
```

After the first loop iteration, the scaling kernel and JPEG encoding will run async on the CUDA stream, while it already starts decoding of the next frame via NvPipe.

Hope that helps!
Tim

**Comment by bootrino** [comment]
Thanks Tim I'll give it a go.

May I ask one more thing please?

It would be an enormous help if there was even a single example C program that showed how to use this lib with C instead of C++  I tried to include NvPipe in a C program and due to my lack of C experience failed utterly.  Here is what happened:

```
ubuntu@ubuntu-nvidia:~/devel/NvPipe-master$ gcc helloworld.c
In file included from helloworld.c:2:
./build/include/NvPipe.h:44:8: error: expected identifier or ‘(’ before string constant
 extern "C"
        ^~~
ubuntu@ubuntu-nvidia:~/devel/NvPipe-master$ cat helloworld.c
#include <stdio.h>
#include "./build/include/NvPipe.h"

int main()
{
    printf( "Hello world.\n" );
}

ubuntu@ubuntu-nvidia:~/devel/NvPipe-master$

```

Thanks greatly for your awesome program.
