### ISSUE TITLE
encoded data creates corrupted video file

### ISSUE THREAD

**Issue by jackcaron** [NVIDIA/NvPipe#7]
Hi guys,

We are trying to create a stream from our OpenGL renderer over the web. I basically followed the EGL example you have and then choose to send that over TCP. But in the web browser, the video doesn't play.

I decided to save the output into a file and I'm getting this one here:
https://www.dropbox.com/s/513axsne97u327b/test.mp4?dl=0

VLC can't play it and I actually managed to play it with another application that had to download a very obscure plugin, but it plays it. If opened on Windows, some video players say the file is corrupted.

There's probably something very minor missing in here to have a valid file and be able to stream it in the browser.

This is how my encoder is created:
```c++
const int QUALITY = 2;
const int FPS = 30;
encoder = nvpipe_create_encoder(NVPIPE_H264_NV, width*height*QUALITY*FPS*0.07);
```
I tried different values for the bit rate, but didn't change anything.

Thanks

**Comment by jackcaron** [comment]
Our guess is that it's missing the MP4 header (*still not sure how to write that one yet*), but if we want an endless stream, is there an alternative?

Also, if we change the extension of the file above to *h264*, now it opens in VLC. So the data is correct, but it's definitely not a correct *mp4* file.

**Comment by tbiedert** [comment]
Hi, thanks for reaching out!

You are correct: NvPipe outputs a raw H.264 stream, which is obviously not valid MP4. MP4 is a container format which can contain multiple streams, such as a H.264 video stream and multiple audio streams.

For your browser streaming efforts you will have to generate MP4 headers for the H.264 packets on the fly. This boils down to an initial main header for the container contents (e.g. codec, resolution, frame rate, etc.) and then for each frame a small frame header. Please check the MP4 specification. Maybe libavformat could be an option.

Hope that helps!

Best,
Tim

**Comment by jackcaron** [comment]
@tbiedert thanks a lot for the fast answer. This confirm our suspicions here. And we didn't know we needed an header per frame.

Thanks again.
