### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by raghs7** [NVIDIA/NvPipe#70]
I am having trouble building nvpExampleEGL. 
The environment is Windows 10 with VS2017. I get this error when I try to build cmake project
Could NOT find EGL (missing: EGL_LIBRARY EGL_opengl_LIBRARY EGL_INCLUDE_DIR) 

How do I install EGL libraries to Visual Studio 2017?

**Comment by tbiedert** [comment]
EGL is Linux only.

**Comment by raghs7** [comment]
Do you think implementation of EGL ANGLE from Google would work ? 
https://github.com/google/angle/tree/master/src/libEGL

**Comment by tbiedert** [comment]
I guess you can give it a try.  Only question is if you really need EGL on Windows. What are you trying to achieve?

**Comment by raghs7** [comment]
I am merely playing around to understand gl+encode+decode latency .

**Comment by tbiedert** [comment]
Okay, in this case I suggest you just create a normal GL context, e.g., via GLFW.
