### ISSUE TITLE
Question: Can I encoder more than 2 streams?

### ISSUE THREAD

**Issue by shi-yan** [NVIDIA/NvPipe#71]
Hello,

nvenc has a limit of 2 encoding streams at most on Geforce. But if we have multiple GPUs in the system, can we have more than 2 encoding streams? Is there a way to select which GPU to use for video encoding?

Thanks

**Comment by Saentist** [comment]
https://github.com/keylase/nvidia-patch
Cheap marketing to buy quadro is to lock by software sessions and color's to same board and chip GeForce.

**Comment by tbiedert** [comment]
Thanks for reaching out!

No, the same limit still applies with multiple GeForce cards. Find some similar questions on the official Video Codec SDK forums below:
- [Multiple encode(nvenc) session on GTX 1080](https://devtalk.nvidia.com/default/topic/1026582/video-codec-and-optical-flow-sdk/multiple-encode-nvenc-session-on-gtx-1080/post/5221990/#5221990)
- [2x GTX1050 and only two encoding streams?](https://devtalk.nvidia.com/default/topic/1022970/video-codec-and-optical-flow-sdk/2x-gtx1050-and-only-two-encoding-streams-/post/5204902/#5204902)

NvPipe simply uses the existing CUDA context when creating an encoder (or creates one if necessary). So to select the encoding device, you can just use `cudaSetDevice`.

Hope that helps!
Tim
