### ISSUE TITLE
Format checked does not match exception message

### ISSUE THREAD

**Issue by bootrino** [NVIDIA/NvPipe#73]
The line above checks for a certain format which does not match the exception message on the next line is this correct?

https://github.com/NVIDIA/NvPipe/blob/34f699333b6913e3f8811d7a731e9cec30f4bf12/src/NvPipe.cu#L545
https://github.com/NVIDIA/NvPipe/blob/34f699333b6913e3f8811d7a731e9cec30f4bf12/src/NvPipe.cu#L546

also here:

https://github.com/NVIDIA/NvPipe/blob/34f699333b6913e3f8811d7a731e9cec30f4bf12/src/NvPipe.cu#L575
https://github.com/NVIDIA/NvPipe/blob/34f699333b6913e3f8811d7a731e9cec30f4bf12/src/NvPipe.cu#L576

also here:

https://github.com/NVIDIA/NvPipe/blob/34f699333b6913e3f8811d7a731e9cec30f4bf12/src/NvPipe.cu#L902
https://github.com/NVIDIA/NvPipe/blob/34f699333b6913e3f8811d7a731e9cec30f4bf12/src/NvPipe.cu#L903

also here

https://github.com/NVIDIA/NvPipe/blob/34f699333b6913e3f8811d7a731e9cec30f4bf12/src/NvPipe.cu#L867
https://github.com/NVIDIA/NvPipe/blob/34f699333b6913e3f8811d7a731e9cec30f4bf12/src/NvPipe.cu#L868

**Comment by tbiedert** [comment]
Thanks, good catch!    Those are leftovers from a previous version.

Fixed in https://github.com/NVIDIA/NvPipe/commit/b3d0a7511052824ff0481fa6eecb3e95eac1a722.
