### ISSUE TITLE
HEVC/H.265 encoding through Jetson Nano?

### ISSUE THREAD

**Issue by JeyP4** [NVIDIA/NvPipe#75]
Hello nVidia

Is NvPipe is the ideal way to encode USB camera stream attached to Jetson Nano?
I want to encode streams of 4 camera attached to nano and send it through ROS network.

I have also gone through
[Encoding USB camera stream to h.264 or h.265
](https://devtalk.nvidia.com/default/topic/1050953/jetson-nano/encoding-usb-camera-stream-to-h-264-or-h-265/)
Thanks

**Comment by tbiedert** [comment]
NvPipe is based on the Video Codec SDK, which is targeting x64 and ppc64le.

On Jetson, you can use the [low-level API](https://docs.nvidia.com/jetson/l4t-multimedia/l4t_mm_01_video_encode_group.html) or [accelerated GStreamer](https://developer.nvidia.com/embedded/dlc/l4t-accelerated-gstreamer-guide-32-2).

Hope that helps!
