### ISSUE TITLE
Why use int64_t and uint64_t?

### ISSUE THREAD

**Issue by shenning00** [NVIDIA/NvPipe#76]
Seems like almost all of these specific 64bit types could be replace with the more common size_t type. Or perhaps variables like bitrate could be some other type. 

Or, could you elaborate on why these specific types are used?

**Comment by tbiedert** [comment]
Thanks, interesting question!

I personally prefer to use the explicit types, especially in regard to ABI compatibility. IIRC size_t is implementation specific and just defined as an unsigned integer type.  
Of course in practice it usually comes down to a uint64_t. 

Personal taste, I guess.

Do you have any practical problem with the current types?

Thanks,
Tim
