### ISSUE TITLE
Why OpenGL interface is limited to RGBA32 format?

### ISSUE THREAD

**Issue by yangrc1234** [NVIDIA/NvPipe#79]
I was trying to compress GL_R16 format opengl texture losslessly, but it seems opengl interface somehow only supports RGBA32.  
I saw on CUDA api page that cuda opengl interop could work with R8, R16, R32 format etc.  Is there any specific reason that these formats can't be used with NvPipe?

**Comment by tbiedert** [comment]
Yes, you can get creative with different formats. A lot is conceivable but not implemented in NvPipe as it was just not required at the time.

That being said, I suggest you implement what you need directly using the NvCodec wrappers from Video Codec SDK. Feel free to check the NvPipe source for some inspiration. There are more samples in the SDK.

I will probably add a deprecation notice to NvPipe soon.

Thanks,
Tim
